#!/bin/bash
set -euo pipefail

# shellcheck source=_test_env.sh
source "$(dirname "${BASH_SOURCE[0]}")/_test_env.sh"

# Manual interactive E2E fixture generator.
#
# This is intentionally not named test_*.sh, so tests/test.sh --unit
# will not discover it.  Running this script creates a throwaway git
# repo with a swarm.json that exercises the manual scenarios we have
# been testing by hand:
#
# - numbered headless Claude and Codex agents;
# - an omitted-count Claude profile for interactive-only use;
# - a count: 0 Codex profile for interactive-only use;
# - Codex ChatGPT auth.json mounting;
# - Claude OAuth env forwarding;
# - dashboard configured rows before containers exist;
# - dashboard I* rows for interactive containers;
# - dashboard P row, with P tailing its logs and lowercase p
#   starting the post-process run;
# - post_process.setup override that runs a lighter post-process
#   setup instead of inheriting the top-level setup.
#
# The generated config uses normal prompts and max_idle=3.  It does
# not include a timeboxed "keep running for N minutes" prompt.  Stop
# agents manually once the scenario has been observed, or let the
# short idle threshold finish the run naturally.

usage() {
    cat <<'HELP'
Usage: tests/manual_interactive_e2e.sh [TARGET_DIR]

Create a throwaway repo for manually exercising interactive swarms.

When TARGET_DIR is omitted, a unique repo is created under /tmp.
When TARGET_DIR is provided, it must be empty or not exist yet.

The script does not launch agents.  It writes MANUAL_STEPS.md in the
new repo with the command sequence to run by hand.
HELP
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

TESTS_DIR="$(cd "$(dirname "$0")" && pwd)"
SWARM_DIR="$(cd "$TESTS_DIR/.." && pwd)"

if [ -n "${1:-}" ]; then
    REPO_DIR="$1"
    if [ -e "$REPO_DIR" ] \
            && [ -n "$(find "$REPO_DIR" -mindepth 1 -maxdepth 1 \
                -print -quit 2>/dev/null)" ]; then
        echo "ERROR: TARGET_DIR exists and is not empty: $REPO_DIR" >&2
        exit 1
    fi
    mkdir -p "$REPO_DIR"
else
    PARENT_DIR="$(mktemp -d /tmp/claude-swarm-manual.XXXXXX)"
    SUFFIX="${PARENT_DIR##*.}"
    REPO_DIR="${PARENT_DIR}/manual-swarm-${SUFFIX}"
    mkdir -p "$REPO_DIR"
fi

REPO_DIR="$(cd "$REPO_DIR" && pwd)"

write_wrapper() {
    local output="$1" target="$2"
    {
        printf '#!/bin/bash\n'
        printf 'set -euo pipefail\n'
        printf 'exec %q "$@"\n' "$target"
    } > "$output"
    chmod +x "$output"
}

mkdir -p \
    "$REPO_DIR/.claude" \
    "$REPO_DIR/prompts" \
    "$REPO_DIR/scripts" \
    "$REPO_DIR/test-results"

write_wrapper "$REPO_DIR/launch.sh" "$SWARM_DIR/launch.sh"
write_wrapper "$REPO_DIR/dashboard.sh" "$SWARM_DIR/dashboard.sh"
write_wrapper "$REPO_DIR/harvest.sh" "$SWARM_DIR/harvest.sh"

cat > "$REPO_DIR/README.md" <<'EOF'
# claude-swarm manual interactive fixture

This repository is generated by `tests/manual_interactive_e2e.sh`.
It is a disposable target for manually exercising headless agents,
interactive containers, auth forwarding, dashboard rendering, harvest,
and post-process behavior.

The generated prompts are intentionally normal task prompts.  They do
not ask agents to wait for a timer.  The swarm config uses
`max_idle: 3` so the run can finish naturally; stop the
run manually when you have observed the behavior you need.
EOF

cat > "$REPO_DIR/AGENTS.md" <<'EOF'
# Manual Smoke Instructions

This repo is disposable.  Keep changes small, commit them, and avoid
network access except for the model CLI call itself.

For headless smoke work, write only under `test-results/`.  For manual
interactive work, create one obvious file under `test-results/`, commit
it, and exit the shell or native UI so the branch is pushed.
EOF

cat > "$REPO_DIR/.claude/CLAUDE.md" <<'EOF'
# Claude Context

This is a manual claude-swarm smoke fixture.  Prefer direct shell
commands, keep commits small, and write observable evidence under
`test-results/`.
EOF

cat > "$REPO_DIR/scripts/setup.sh" <<'EOF'
#!/bin/bash
set -euo pipefail

mkdir -p test-results
setup_id="${SWARM_INTERACTIVE_BRANCH:-agent-${AGENT_ID:-unknown}}"
setup_id="${setup_id//\//-}"
setup_id="$(printf '%s' "$setup_id" | tr -c '[:alnum:]_.-' '-')"
setup_log="test-results/setup-${setup_id}.log"

# Keep setup output unique so harvested interactive branches do not
# collide when users follow the runbook's broad `git add test-results`.
{
    printf 'setup ran at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'agent=%s driver=%s model=%s\n' \
        "${AGENT_ID:-unknown}" \
        "${SWARM_DRIVER:-unknown}" \
        "${SWARM_MODEL:-unknown}"
    printf 'branch=%s\n' "${SWARM_INTERACTIVE_BRANCH:-}"
    printf 'profile=%s\n' "${SWARM_INTERACTIVE_PROFILE:-}"
} >> "$setup_log"
EOF
chmod +x "$REPO_DIR/scripts/setup.sh"

cat > "$REPO_DIR/scripts/post-setup.sh" <<'EOF'
#!/bin/bash
set -euo pipefail

# Lighter setup used only for the post-process pass.  swarm.json sets
# post_process.setup to this script, so launch.sh runs it instead of
# inheriting the heavier top-level scripts/setup.sh.  The unique marker
# makes the override observable: it proves the post-process container
# ran this lighter script and did not redo the top-level setup.
mkdir -p test-results
{
    printf 'POST_SETUP_RAN at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'driver=%s model=%s\n' \
        "${SWARM_DRIVER:-unknown}" \
        "${SWARM_MODEL:-unknown}"
} >> test-results/post-process-setup.log
EOF
chmod +x "$REPO_DIR/scripts/post-setup.sh"

cat > "$REPO_DIR/prompts/headless.md" <<'EOF'
You are running a manual claude-swarm smoke test in a disposable repo.

Make one small, unique commit that proves this numbered agent ran:

1. Inspect `git status --short` and `README.md`.
2. Create `test-results/headless-${AGENT_ID:-unknown}.md` if it does
   not already exist.  Use a shell command so `${AGENT_ID}` expands in
   the container.
3. Include the agent id, driver, model, UTC time, and the first line of
   `git rev-parse --short HEAD`.
4. Commit the file with a concise message.

If your marker file already exists, make no changes and exit normally.
Do not sleep, wait for a timer, or run an infinite loop.
EOF

cat > "$REPO_DIR/prompts/manual.md" <<'EOF'
Manual interactive smoke prompt.

Verify the active driver and auth, then make one small commit:

1. For Claude Code, run `claude auth status` and `claude --version`.
2. For Codex, run `test -s ~/.codex/auth.json` and `codex --version`.
3. Create or append `test-results/manual-${SWARM_INTERACTIVE_PROFILE}.md`.
4. Include the branch, profile, driver, model, and UTC time.
5. Commit the file and exit the shell or native UI.

Use shell commands so the environment variables expand inside the
container.  Do not leave uncommitted changes unless the scenario is
specifically testing the dashboard `dirty` state.
EOF

cat > "$REPO_DIR/prompts/post-process.md" <<'EOF'
You are the post-process agent for a manual claude-swarm smoke test.

First run this guard.  If it succeeds, make no changes and exit:

```bash
test -f test-results/post-process-summary.md \
  && grep -q '^POST_PROCESS_DONE$' test-results/post-process-summary.md
```

If the guard fails, write `test-results/post-process-summary.md` once:

1. List files in `test-results/`, excluding `post-process-summary.md`.
2. Note whether `agent_logs/interactive_state` exists.
3. End with `POST_PROCESS_DONE` on its own line.
4. Commit the summary.

Do not sleep, wait for a timer, or run an infinite loop.
EOF

cat > "$REPO_DIR/swarm.json" <<'EOF'
{
  "title": "Interactive E2E smoke",
  "prompt": "prompts/headless.md",
  "setup": "scripts/setup.sh",
  "max_idle": 3,
  "driver": "claude-code",
  "tag": "manual-smoke",
  "agents": [
    {
      "name": "claude-headless",
      "count": 3,
      "model": "claude-opus-4-6",
      "auth": "oauth",
      "context": "slim",
      "tag": "claude-headless"
    },
    {
      "name": "codex-headless",
      "count": 2,
      "driver": "codex-cli",
      "model": "gpt-5.4",
      "effort": "medium",
      "auth": "chatgpt",
      "context": "slim",
      "tag": "codex-headless"
    },
    {
      "name": "claude-manual",
      "model": "claude-opus-4-6",
      "auth": "oauth",
      "context": "slim",
      "prompt": "prompts/manual.md",
      "tag": "claude-manual"
    },
    {
      "name": "codex-manual",
      "count": 0,
      "driver": "codex-cli",
      "model": "gpt-5.4",
      "effort": "medium",
      "auth": "chatgpt",
      "context": "slim",
      "prompt": "prompts/manual.md",
      "tag": "codex-manual"
    }
  ],
  "post_process": {
    "prompt": "prompts/post-process.md",
    "setup": "scripts/post-setup.sh",
    "driver": "codex-cli",
    "model": "gpt-5.4",
    "effort": "medium",
    "auth": "chatgpt",
    "context": "slim",
    "tag": "post-process",
    "max_idle": 3
  }
}
EOF

cat > "$REPO_DIR/env.example" <<'EOF'
# Copy these exports into your shell.  Do not commit real secrets.
#
# Claude OAuth is needed for the Claude headless and manual profiles.
# If you do not export it, launch.sh should warn and the dashboard auth
# column should not claim the Claude containers are authenticated.
export CLAUDE_CODE_OAUTH_TOKEN='replace-me'

# Codex ChatGPT auth uses the host auth file.  By default this is:
#   ~/.codex/auth.json
# Set CODEX_AUTH_JSON only if you keep the file somewhere else.
# export CODEX_AUTH_JSON="$HOME/.codex/auth.json"

# Optional fallback if you change Codex profiles to auth=apikey.
# export OPENAI_API_KEY='replace-me'
EOF

cat > "$REPO_DIR/MANUAL_STEPS.md" <<EOF
# Manual Interactive E2E Steps

Run these commands one at a time from this repo:

\`\`\`bash
cd "$REPO_DIR"
export SWARM_CONFIG=swarm.json
\`\`\`

## 0. Credential Preflight

Export Claude OAuth in the shell that will run \`launch.sh\`.  Inline
environment variables only affect the one command they prefix, so use
\`export\` when you plan to run \`start\`, \`shell\`, and \`chat\`
separately.

\`\`\`bash
export CLAUDE_CODE_OAUTH_TOKEN='...'
test -s "\${CODEX_AUTH_JSON:-\$HOME/.codex/auth.json}"
\`\`\`

Expected result:

- The \`test -s\` command exits 0 for Codex ChatGPT auth.
- Do not paste secrets into files in this repo.

## 1. Dashboard Before Launch

\`\`\`bash
./dashboard.sh
\`\`\`

Expected result:

- Numbered rows 1-5 render from \`swarm.json\` as \`configured\`.
- They should show real model, driver, and auth values, not
  \`unknown\` / \`not found\`.
- Omitted \`count\` on \`claude-manual\` and \`count: 0\` on
  \`codex-manual\` should not add numbered rows.
- The post-process row should appear as \`P\`, the same letter as the
  \`P\` key that tails its logs once it exists.
- The footer should show \`[p] post-process\` -- lowercase \`p\`
  starts the run.

Press \`q\` to exit.

## 2. Start Headless Agents With Dashboard

\`\`\`bash
./launch.sh start --dashboard
\`\`\`

Expected result:

- Five numbered containers start: 3 Claude OAuth and 2 Codex ChatGPT.
- The dashboard header reports 5 agents.
- Press \`1\` through \`5\` to inspect numbered-agent logs.
- \`P\` should only tail post-process logs after a post-process
  container exists; the logs hint becomes \`[1-9/P]\` then.
- \`p\` should ask for confirmation before starting post-process.
  Once the container exists, the \`[p] post-process\` start hint
  disappears (stop with \`s\` before starting another run).

This fixture uses \`max_idle: 3\` and normal prompts, so agents can
finish naturally.  Once you have seen enough, press \`s\` in the
dashboard or run:

\`\`\`bash
./launch.sh stop
\`\`\`

## 3. Codex Manual Shell

\`\`\`bash
./launch.sh shell --agent codex-manual
\`\`\`

Inside the container, run:

\`\`\`bash
test -s ~/.codex/auth.json && echo "codex auth mounted"
codex --version
cat prompts/manual.md
mkdir -p test-results
{
  printf 'profile=%s\\n' "\${SWARM_INTERACTIVE_PROFILE}"
  printf 'branch=%s\\n' "\${SWARM_INTERACTIVE_BRANCH}"
  printf 'driver=%s\\n' "\${SWARM_DRIVER}"
  printf 'model=%s\\n' "\${SWARM_MODEL}"
  date -u '+time=%Y-%m-%dT%H:%M:%SZ'
} > "test-results/manual-\${SWARM_INTERACTIVE_PROFILE}.md"
git add test-results
git commit -m "Record Codex manual smoke"
exit
\`\`\`

Expected result:

- The auth.json check prints \`codex auth mounted\`.
- Exiting pushes a \`swarm/*/interactive-codex-manual-*\` branch.

## 4. Claude Manual Shell

\`\`\`bash
./launch.sh shell --agent claude-manual
\`\`\`

Inside the container, run:

\`\`\`bash
claude auth status
claude --version
cat prompts/manual.md
mkdir -p test-results
{
  printf 'profile=%s\\n' "\${SWARM_INTERACTIVE_PROFILE}"
  printf 'branch=%s\\n' "\${SWARM_INTERACTIVE_BRANCH}"
  printf 'driver=%s\\n' "\${SWARM_DRIVER}"
  printf 'model=%s\\n' "\${SWARM_MODEL}"
  date -u '+time=%Y-%m-%dT%H:%M:%SZ'
} > "test-results/manual-\${SWARM_INTERACTIVE_PROFILE}.md"
git add test-results
git commit -m "Record Claude manual smoke"
exit
\`\`\`

Expected result:

- \`claude auth status\` reports the injected OAuth credential.
- Exiting pushes a \`swarm/*/interactive-claude-manual-*\` branch.

## 5. Native Interactive UIs

Use these only when you want to test the actual driver UI, not just the
container shell:

\`\`\`bash
./launch.sh chat --agent codex-manual
./launch.sh chat --agent claude-manual
\`\`\`

When the UI opens, paste the contents of \`prompts/manual.md\`.  Ask
the agent to make and commit one file under \`test-results/\`, then
exit the UI.  The container exit hook should push the interactive
branch.

## 6. Dashboard Interactive Rows

\`\`\`bash
./dashboard.sh
\`\`\`

Expected result:

- Interactive containers appear as \`I1\`, \`I2\`, and so on.
- A committed but unharvested interactive branch should show
  \`unharvested\`.
- A running shell with uncommitted changes should show \`dirty\`.
- After harvest, the row should show \`harvested\`.

## 7. Post-Process From Dashboard

\`\`\`bash
./dashboard.sh
\`\`\`

Press \`p\`, confirm with \`y\`, and watch the \`P\` row.  After the
post-process container exists, uppercase \`P\` tails its logs and the
\`[p] post-process\` start hint disappears.  Use \`s\` or
\`./launch.sh stop\` before starting a new post-process run.

Equivalent non-dashboard command:

\`\`\`bash
./launch.sh post-process
\`\`\`

Expected result:

- Post-process uses the Codex ChatGPT profile from \`post_process\`.
- Before the prompt runs, the container executes
  \`scripts/post-setup.sh\` (from \`post_process.setup\`), which appends
  a \`POST_SETUP_RAN\` line to \`test-results/post-process-setup.log\`.
  This is the lighter post-process setup; the heavier top-level
  \`scripts/setup.sh\` is not redone here.
- It writes \`test-results/post-process-summary.md\`.
- The summary lists \`post-process-setup.log\`, so the override stays
  visible after harvest.
- The summary ends with \`POST_PROCESS_DONE\`.

The \`post_process.setup\` key has three modes.  This fixture ships the
override (a path); to try the others, edit \`swarm.json\`:

- Path (the default here): \`"setup": "scripts/post-setup.sh"\` runs
  that lighter script for the post-process pass only.
- Skip: \`"setup": false\` or \`"setup": ""\` runs no setup, so a heavy
  top-level setup is not repeated.  \`post-process-setup.log\` is then
  absent.
- Inherit: remove the \`setup\` key from \`post_process\` to reuse the
  top-level \`scripts/setup.sh\`; a \`test-results/setup-*.log\` for the
  post-process pass appears instead.

## 8. Harvest And Inspect

\`\`\`bash
./harvest.sh --dry
./harvest.sh
git log --oneline --max-count=16
find test-results -maxdepth 1 -type f -print | sort
\`\`\`

Expected result:

- Headless agent commits, interactive commits, and post-process output
  are all merge candidates.
- Harvest merges \`agent-work\` plus \`swarm/*/interactive-*\`
  branches into the current branch.
- Interactive setup logs are branch-specific, so harvest should not
  conflict on a shared \`test-results/setup.log\`.

## Cleanup

\`\`\`bash
./launch.sh stop
\`\`\`

Optional cleanup for this disposable repo's Docker artifacts:

\`\`\`bash
docker ps -a --format '{{.Names}}' | grep "\$(basename "\$PWD")-agent" || true
\`\`\`

Remove the temp directory when you are done:

\`\`\`bash
rm -rf "$REPO_DIR"
\`\`\`
EOF

cat > "$REPO_DIR/manual-workflow.sh" <<'EOF'
#!/bin/bash
set -euo pipefail

# This helper prints the manual runbook path and exits.
#
# Keep it as a reminder that the workflow is intentionally manual:
# launching these agents can spend real API tokens, and the point is
# to inspect dashboard states, auth behavior, interactive branches, and
# post-process behavior with a human in the loop.

printf 'Read MANUAL_STEPS.md, then run the commands one at a time.\n'
printf 'Suggested first command:\n\n'
printf '  export SWARM_CONFIG=swarm.json\n'
printf '  ./dashboard.sh\n'
EOF
chmod +x "$REPO_DIR/manual-workflow.sh"

cd "$REPO_DIR"
if git init -b main >/dev/null 2>&1; then
    :
else
    git init >/dev/null
    git checkout -b main >/dev/null 2>&1 || true
fi
git config user.name "Manual Swarm Tester"
git config user.email "manual-swarm@example.invalid"
git add .
git commit -m "Create manual swarm smoke fixture" >/dev/null

cat <<EOF
Created manual interactive E2E repo:

  $REPO_DIR

Next commands:

  cd "$REPO_DIR"
  export SWARM_CONFIG=swarm.json
  ./dashboard.sh

Read the full manual runbook:

  $REPO_DIR/MANUAL_STEPS.md
EOF
